// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/fruits_embedded_channel_message.proto

package io.github.joshuadeguzman;

public final class FruitsEmbeddedChannelMessageOuterClass {
  private FruitsEmbeddedChannelMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FruitsEmbeddedChannelMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FruitsEmbeddedChannelMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string route = 1;</code>
     */
    java.lang.String getRoute();
    /**
     * <code>string route = 1;</code>
     */
    com.google.protobuf.ByteString
        getRouteBytes();

    /**
     * <code>.User user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>.User user = 2;</code>
     */
    io.github.joshuadeguzman.UserOuterClass.User getUser();
    /**
     * <code>.User user = 2;</code>
     */
    io.github.joshuadeguzman.UserOuterClass.UserOrBuilder getUserOrBuilder();

    /**
     * <code>bool isOwnProfile = 3;</code>
     */
    boolean getIsOwnProfile();
  }
  /**
   * Protobuf type {@code FruitsEmbeddedChannelMessage}
   */
  public  static final class FruitsEmbeddedChannelMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FruitsEmbeddedChannelMessage)
      FruitsEmbeddedChannelMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FruitsEmbeddedChannelMessage.newBuilder() to construct.
    private FruitsEmbeddedChannelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FruitsEmbeddedChannelMessage() {
      route_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FruitsEmbeddedChannelMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              route_ = s;
              break;
            }
            case 18: {
              io.github.joshuadeguzman.UserOuterClass.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(io.github.joshuadeguzman.UserOuterClass.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              isOwnProfile_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.internal_static_FruitsEmbeddedChannelMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.internal_static_FruitsEmbeddedChannelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.class, io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.Builder.class);
    }

    public static final int ROUTE_FIELD_NUMBER = 1;
    private volatile java.lang.Object route_;
    /**
     * <code>string route = 1;</code>
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        route_ = s;
        return s;
      }
    }
    /**
     * <code>string route = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private io.github.joshuadeguzman.UserOuterClass.User user_;
    /**
     * <code>.User user = 2;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public io.github.joshuadeguzman.UserOuterClass.User getUser() {
      return user_ == null ? io.github.joshuadeguzman.UserOuterClass.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public io.github.joshuadeguzman.UserOuterClass.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int ISOWNPROFILE_FIELD_NUMBER = 3;
    private boolean isOwnProfile_;
    /**
     * <code>bool isOwnProfile = 3;</code>
     */
    public boolean getIsOwnProfile() {
      return isOwnProfile_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRouteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, route_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      if (isOwnProfile_ != false) {
        output.writeBool(3, isOwnProfile_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRouteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, route_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      if (isOwnProfile_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isOwnProfile_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage)) {
        return super.equals(obj);
      }
      io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage other = (io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage) obj;

      if (!getRoute()
          .equals(other.getRoute())) return false;
      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (getIsOwnProfile()
          != other.getIsOwnProfile()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRoute().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + ISOWNPROFILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOwnProfile());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FruitsEmbeddedChannelMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FruitsEmbeddedChannelMessage)
        io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.internal_static_FruitsEmbeddedChannelMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.internal_static_FruitsEmbeddedChannelMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.class, io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.Builder.class);
      }

      // Construct using io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        route_ = "";

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        isOwnProfile_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.internal_static_FruitsEmbeddedChannelMessage_descriptor;
      }

      @java.lang.Override
      public io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage getDefaultInstanceForType() {
        return io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage build() {
        io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage buildPartial() {
        io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage result = new io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage(this);
        result.route_ = route_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.isOwnProfile_ = isOwnProfile_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage) {
          return mergeFrom((io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage other) {
        if (other == io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage.getDefaultInstance()) return this;
        if (!other.getRoute().isEmpty()) {
          route_ = other.route_;
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.getIsOwnProfile() != false) {
          setIsOwnProfile(other.getIsOwnProfile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object route_ = "";
      /**
       * <code>string route = 1;</code>
       */
      public java.lang.String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          route_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string route = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRouteBytes() {
        java.lang.Object ref = route_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          route_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder setRoute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        route_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder clearRoute() {
        
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder setRouteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        route_ = value;
        onChanged();
        return this;
      }

      private io.github.joshuadeguzman.UserOuterClass.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.joshuadeguzman.UserOuterClass.User, io.github.joshuadeguzman.UserOuterClass.User.Builder, io.github.joshuadeguzman.UserOuterClass.UserOrBuilder> userBuilder_;
      /**
       * <code>.User user = 2;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public io.github.joshuadeguzman.UserOuterClass.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? io.github.joshuadeguzman.UserOuterClass.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder setUser(io.github.joshuadeguzman.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder setUser(
          io.github.joshuadeguzman.UserOuterClass.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder mergeUser(io.github.joshuadeguzman.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              io.github.joshuadeguzman.UserOuterClass.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public io.github.joshuadeguzman.UserOuterClass.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User user = 2;</code>
       */
      public io.github.joshuadeguzman.UserOuterClass.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              io.github.joshuadeguzman.UserOuterClass.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.joshuadeguzman.UserOuterClass.User, io.github.joshuadeguzman.UserOuterClass.User.Builder, io.github.joshuadeguzman.UserOuterClass.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.joshuadeguzman.UserOuterClass.User, io.github.joshuadeguzman.UserOuterClass.User.Builder, io.github.joshuadeguzman.UserOuterClass.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private boolean isOwnProfile_ ;
      /**
       * <code>bool isOwnProfile = 3;</code>
       */
      public boolean getIsOwnProfile() {
        return isOwnProfile_;
      }
      /**
       * <code>bool isOwnProfile = 3;</code>
       */
      public Builder setIsOwnProfile(boolean value) {
        
        isOwnProfile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isOwnProfile = 3;</code>
       */
      public Builder clearIsOwnProfile() {
        
        isOwnProfile_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FruitsEmbeddedChannelMessage)
    }

    // @@protoc_insertion_point(class_scope:FruitsEmbeddedChannelMessage)
    private static final io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage();
    }

    public static io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FruitsEmbeddedChannelMessage>
        PARSER = new com.google.protobuf.AbstractParser<FruitsEmbeddedChannelMessage>() {
      @java.lang.Override
      public FruitsEmbeddedChannelMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FruitsEmbeddedChannelMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FruitsEmbeddedChannelMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FruitsEmbeddedChannelMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.joshuadeguzman.FruitsEmbeddedChannelMessageOuterClass.FruitsEmbeddedChannelMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FruitsEmbeddedChannelMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FruitsEmbeddedChannelMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protos/fruits_embedded_channel_message" +
      ".proto\032\021protos/user.proto\"X\n\034FruitsEmbed" +
      "dedChannelMessage\022\r\n\005route\030\001 \001(\t\022\023\n\004user" +
      "\030\002 \001(\0132\005.User\022\024\n\014isOwnProfile\030\003 \001(\010B\032\n\030i" +
      "o.github.joshuadeguzmanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.joshuadeguzman.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_FruitsEmbeddedChannelMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FruitsEmbeddedChannelMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FruitsEmbeddedChannelMessage_descriptor,
        new java.lang.String[] { "Route", "User", "IsOwnProfile", });
    io.github.joshuadeguzman.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
